export const WEATHER_ICONS = 
  { 'Clear sky': '/icons/sun.svg',
  'Mainly clear':  '/icons/sun.svg',
  'Partly cloudy': '/icons/cloud-sun.svg',
  'Overcast': '/icons/cloud.svg',
  'Fog': '/icons/cloud-fog.svg',
  'Depositing rime fog': '/icons/cloud-fog.svg',
  'Light drizzle': '/icons/cloud-rain.svg',
  'Drizzle': '/icons/cloud-rain.svg',
  'Dense drizzle': '/icons/cloud-rain.svg',
  'Light freezing drizzle': '/icons/cloud-rain.svg',
  'Dense freezing drizzle': '/icons/cloud-rain.svg',
  'Slight rain': '/icons/cloud-rain.svg',
  'Rain': '/icons/cloud-rain.svg',
  'Heavy rain': '/icons/cloud-raindrops.svg',
  'Freezing rain': '/icons/cloud-raindrops.svg',
  'Heavy freezing rain': '/icons/cloud-raindrops.svg',
  'Slight snow fall': '/icons/cloud-snow.svg',
  'Snow fall': '/icons/cloud-snowflakes.svg',
  'Heavy snow fall': '/icons/cloud-snowflakes.svg',
  'Snow grains': '/icons/cloud-snowflakes.svg',
  'Violent rain showers': '/icons/cloud-raindrops.svg',
  'Violent rain showers': '/icons/cloud-raindrops.svg',
  'Violent rain showers': '/icons/cloud-raindrops.svg',
  'Slight snow showers': '/icons/cloud-snowflakes.svg',
 'Heavy snow showers': '/icons/cloud-snowflakes.svg',
 'Thunderstorm': '/icons/cloud-lighting.svg', 
 'Thunderstorm with slight hail': '/icons/cloud-raindrops.svg',
 'Thunderstorm with heavy hail': '/icons/cloud-lighting.svg',
}
