export const WEATHER_CODES = [
{ code: 0, description: 'Clear sky', icon: 'PiSunLight' },
{ code: 1, description: 'Mainly clear', icon: 'PiSunDimLight' }, 
{ code: 2, description: 'Partly cloudy', icon: 'BsFillCloudSunFill' },
{ code: 3, description: 'Overcast', icon: 'WiCloud' },
{ code: 45, description: 'Fog', icon: 'PiCloudFogThin' },
{ code: 48, description: 'Depositing rime fog', icon: 'PiCloudFogThin' },
{ code: 51, description: 'Light drizzle', icon: 'PiCloudRainThin' },
{ code: 53, description: 'Drizzle', icon: 'BsFillCloudDrizzleFill' },
{ code: 55, description: 'Dense drizzle', icon: 'BsFillCloudDrizzleFill'},
{ code: 56, description: 'Light freezing drizzle', icon: 'BsFillCloudSleetFill' },
{ code: 57, description: 'Dense freezing drizzle', icon: 'BsFillCloudSleetFill' },
{ code: 61, description: 'Slight rain', icon: 'BsFillCloudDrizzleFill' },
{ code: 63, description: 'Rain', icon: 'BsFillCloudRainFill' },
{ code: 65, description: 'Heavy rain', icon: 'BsFillCloudRainHeavyFill'},
{ code: 66, description: 'Freezing rain', icon: 'BsFillCloudSleetFill' },
{ code: 67, description: 'Heavy freezing rain', icon: 'BsFillCloudSleetFill' },
{ code: 71, description: 'Slight snow fall', icon: 'BsFillCloudSnowFill' },
{ code: 73, description: 'Snow fall', icon: 'BsFillCloudSnowFill' },
{ code: 75, description: 'Heavy snow fall', icon: 'BsFillCloudSnowFill' },
{ code: 77, description: 'Snow grains', icon: 'BsFillCloudHailFill' },
{ code: 80, description: 'Violent rain showers', icon: 'BsFillCloudRainHeavyFill' },
{ code: 81, description: 'Violent rain showers', icon: 'BsFillCloudRainHeavyFill' },
{ code: 82, description: 'Violent rain showers', icon: 'BsFillCloudRainHeavyFill' },
{ code: 85, description: 'Slight snow showers', icon: 'BsFillCloudSnowFill'  },
{ code: 86, description: 'Heavy snow showers', icon: 'BsFillCloudSnowFill'  },
{ code: 95, description: 'Thunderstorm', icon: 'BsFillCloudLightningRainFill'}, 
{ code: 96, description: 'Thunderstorm with slight hail', icon: 'BsFillCloudLightningRainFill' },
{ code: 99, description: 'Thunderstorm with heavy hail', icon: 'BsFillCloudLightningRainFill' },
];
